//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack/Inputs/RPGInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace RPGCharacterAnims
{
    public partial class @RPGInputs : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @RPGInputs()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""RPGInputActions"",
    ""maps"": [
        {
            ""name"": ""RPGCharacter"",
            ""id"": ""3ead366c-a6b7-44d2-8381-0a0b951f5df8"",
            ""actions"": [
                {
                    ""name"": ""AttackL"",
                    ""type"": ""Button"",
                    ""id"": ""12f351ba-2710-419f-bda3-bf2abf737ff4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackR"",
                    ""type"": ""Button"",
                    ""id"": ""01a71673-bab7-492e-8129-87f3109d7a58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Value"",
                    ""id"": ""f6a094d5-bf2c-432a-be73-f32274a37dbd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CastL"",
                    ""type"": ""Button"",
                    ""id"": ""8adf7ca3-6cd8-41b2-b282-20a4241f0a00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CastR"",
                    ""type"": ""Button"",
                    ""id"": ""5dff7773-c15e-405f-beac-d8ef7acba2f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Death"",
                    ""type"": ""Button"",
                    ""id"": ""8fbfea2e-d59e-48dc-ae84-73e9c0d479f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Face"",
                    ""type"": ""Button"",
                    ""id"": ""787a80ae-a794-4ad0-8aad-2e110194e427"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Facing"",
                    ""type"": ""Value"",
                    ""id"": ""dd5a4ce2-a4d1-4d8a-bee7-3759c067ffd6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""5679467b-966e-49db-b5a9-aa9e28fc90d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightHit"",
                    ""type"": ""Button"",
                    ""id"": ""c6381ffb-3d89-4857-b599-53b47c05849c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""43308ce0-cc64-42b2-a9dd-3295b6ef9f15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Relax"",
                    ""type"": ""Button"",
                    ""id"": ""2636d27b-b1c1-4d92-a1e9-29c6e7207dcd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""9b8a647f-12ad-455b-bc4e-d14bc34f084e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shield"",
                    ""type"": ""Button"",
                    ""id"": ""772f991d-0937-4372-b419-8d5bebd81c90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""aafb5408-6a4f-4fd7-a596-caf6387fc87e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponDown"",
                    ""type"": ""Button"",
                    ""id"": ""ebe77173-3d6b-449e-9552-b29a4d28a382"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponLeft"",
                    ""type"": ""Button"",
                    ""id"": ""24b09064-1bea-48ae-b9bd-5f4b46615fff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponRight"",
                    ""type"": ""Button"",
                    ""id"": ""962e1d87-138c-4796-a086-8fce83fa0bd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponUp"",
                    ""type"": ""Button"",
                    ""id"": ""ae0d5111-b008-4443-8ac0-8b971ad35b20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Join"",
                    ""type"": ""Button"",
                    ""id"": ""0cac1077-d2f0-4c42-8379-0ec638b59e0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""28d72250-4b94-4aa3-b36b-227b7dcb5778"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""b752e111-5c96-4c46-bcfb-7113d682a208"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bbdbdafb-66ad-4206-9f76-c60d53269a1b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.125,max=0.925)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""2e85cef7-c1cb-4b22-8597-350bec0aa14d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2120b965-d816-4b44-838a-869511df56c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""826155c0-f5d3-45d0-a964-1cd39e4de24d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""57c3d98e-ba54-40a2-87d3-9640624cf46d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ded9887c-d549-4d24-8f18-e42ff97d6611"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3a2bc915-4b04-443e-b134-8620b71cf761"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57a20f9a-a0cd-425a-82f0-4802a171f039"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""WeaponUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da68dbb3-b1e4-446a-97bc-e0cc755186a6"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c49ee73c-20d1-4fe3-a15a-efb00716c998"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49d9ee54-833f-4704-9579-a66ccde8c535"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AttackL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3e2d08c-ede1-42ec-8252-c857c9312c9c"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""AttackL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0acae91-204f-447c-9ff5-24d26ff3cee5"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AttackR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe5bc54d-a03f-4dbc-b984-c99bf0adf08a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""AttackR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d79770ca-5c77-4b53-ac33-9712a4cb8ee2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ef74780-1c12-4a89-beae-9663888f6cfc"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36a9d2d3-deaf-44e5-8805-5f4731241e0a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Press(pressPoint=0.5,behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a37556aa-5777-4ec8-90d9-f60c3cf4fd79"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Press(pressPoint=0.5,behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CastR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63104a7a-9566-435a-be44-cab8f87e4ab2"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Face"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""444d5689-a373-4ff8-bc62-5a0435ff4833"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),StickDeadzone(min=0.125,max=0.925)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Facing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9417228-53a0-4d27-8d6d-d45b933fcd4e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Death"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c1b111f-b14e-4638-95be-9154e3b9b55e"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d391688-9680-45a3-853b-7f9ec5332177"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19863b85-850a-4781-b0d8-846d0261c5e1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a421ad8-1e28-4dd2-b3f6-b646378349d4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""WeaponDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccc96395-0f4e-4f20-a2b3-fae393c3f49c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1479904d-51b9-43dc-b48b-f60109daef6f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""WeaponLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3ad3153-4b02-4253-90e4-12525fdb642f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""105bfa37-fdf2-4313-9ed7-b6e10cee123f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""WeaponRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f11c46ab-cc0b-4bff-8583-9afa124803f9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0353b89c-fbaa-4822-8080-d489bb9e3064"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Join"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""589f05e8-3250-47a1-8b5d-499b0db66a3a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Join"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db13f25b-e00b-475a-a4de-64d6b3d6a69b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94b73e85-d8bc-47b4-8f5f-74d9a10c9cbb"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa1a3563-a4fc-4b79-97e4-bcbdeb9dc6a9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15f98acb-a2c6-4d73-a415-bc80023d9ba2"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Mouse and Keyboard"",
            ""bindingGroup"": ""Mouse and Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // RPGCharacter
            m_RPGCharacter = asset.FindActionMap("RPGCharacter", throwIfNotFound: true);
            m_RPGCharacter_AttackL = m_RPGCharacter.FindAction("AttackL", throwIfNotFound: true);
            m_RPGCharacter_AttackR = m_RPGCharacter.FindAction("AttackR", throwIfNotFound: true);
            m_RPGCharacter_Block = m_RPGCharacter.FindAction("Block", throwIfNotFound: true);
            m_RPGCharacter_CastL = m_RPGCharacter.FindAction("CastL", throwIfNotFound: true);
            m_RPGCharacter_CastR = m_RPGCharacter.FindAction("CastR", throwIfNotFound: true);
            m_RPGCharacter_Death = m_RPGCharacter.FindAction("Death", throwIfNotFound: true);
            m_RPGCharacter_Face = m_RPGCharacter.FindAction("Face", throwIfNotFound: true);
            m_RPGCharacter_Facing = m_RPGCharacter.FindAction("Facing", throwIfNotFound: true);
            m_RPGCharacter_Jump = m_RPGCharacter.FindAction("Jump", throwIfNotFound: true);
            m_RPGCharacter_LightHit = m_RPGCharacter.FindAction("LightHit", throwIfNotFound: true);
            m_RPGCharacter_Move = m_RPGCharacter.FindAction("Move", throwIfNotFound: true);
            m_RPGCharacter_Relax = m_RPGCharacter.FindAction("Relax", throwIfNotFound: true);
            m_RPGCharacter_Roll = m_RPGCharacter.FindAction("Roll", throwIfNotFound: true);
            m_RPGCharacter_Shield = m_RPGCharacter.FindAction("Shield", throwIfNotFound: true);
            m_RPGCharacter_Aim = m_RPGCharacter.FindAction("Aim", throwIfNotFound: true);
            m_RPGCharacter_WeaponDown = m_RPGCharacter.FindAction("WeaponDown", throwIfNotFound: true);
            m_RPGCharacter_WeaponLeft = m_RPGCharacter.FindAction("WeaponLeft", throwIfNotFound: true);
            m_RPGCharacter_WeaponRight = m_RPGCharacter.FindAction("WeaponRight", throwIfNotFound: true);
            m_RPGCharacter_WeaponUp = m_RPGCharacter.FindAction("WeaponUp", throwIfNotFound: true);
            m_RPGCharacter_Join = m_RPGCharacter.FindAction("Join", throwIfNotFound: true);
            m_RPGCharacter_Kick = m_RPGCharacter.FindAction("Kick", throwIfNotFound: true);
            m_RPGCharacter_Interact = m_RPGCharacter.FindAction("Interact", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // RPGCharacter
        private readonly InputActionMap m_RPGCharacter;
        private IRPGCharacterActions m_RPGCharacterActionsCallbackInterface;
        private readonly InputAction m_RPGCharacter_AttackL;
        private readonly InputAction m_RPGCharacter_AttackR;
        private readonly InputAction m_RPGCharacter_Block;
        private readonly InputAction m_RPGCharacter_CastL;
        private readonly InputAction m_RPGCharacter_CastR;
        private readonly InputAction m_RPGCharacter_Death;
        private readonly InputAction m_RPGCharacter_Face;
        private readonly InputAction m_RPGCharacter_Facing;
        private readonly InputAction m_RPGCharacter_Jump;
        private readonly InputAction m_RPGCharacter_LightHit;
        private readonly InputAction m_RPGCharacter_Move;
        private readonly InputAction m_RPGCharacter_Relax;
        private readonly InputAction m_RPGCharacter_Roll;
        private readonly InputAction m_RPGCharacter_Shield;
        private readonly InputAction m_RPGCharacter_Aim;
        private readonly InputAction m_RPGCharacter_WeaponDown;
        private readonly InputAction m_RPGCharacter_WeaponLeft;
        private readonly InputAction m_RPGCharacter_WeaponRight;
        private readonly InputAction m_RPGCharacter_WeaponUp;
        private readonly InputAction m_RPGCharacter_Join;
        private readonly InputAction m_RPGCharacter_Kick;
        private readonly InputAction m_RPGCharacter_Interact;
        public struct RPGCharacterActions
        {
            private @RPGInputs m_Wrapper;
            public RPGCharacterActions(@RPGInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @AttackL => m_Wrapper.m_RPGCharacter_AttackL;
            public InputAction @AttackR => m_Wrapper.m_RPGCharacter_AttackR;
            public InputAction @Block => m_Wrapper.m_RPGCharacter_Block;
            public InputAction @CastL => m_Wrapper.m_RPGCharacter_CastL;
            public InputAction @CastR => m_Wrapper.m_RPGCharacter_CastR;
            public InputAction @Death => m_Wrapper.m_RPGCharacter_Death;
            public InputAction @Face => m_Wrapper.m_RPGCharacter_Face;
            public InputAction @Facing => m_Wrapper.m_RPGCharacter_Facing;
            public InputAction @Jump => m_Wrapper.m_RPGCharacter_Jump;
            public InputAction @LightHit => m_Wrapper.m_RPGCharacter_LightHit;
            public InputAction @Move => m_Wrapper.m_RPGCharacter_Move;
            public InputAction @Relax => m_Wrapper.m_RPGCharacter_Relax;
            public InputAction @Roll => m_Wrapper.m_RPGCharacter_Roll;
            public InputAction @Shield => m_Wrapper.m_RPGCharacter_Shield;
            public InputAction @Aim => m_Wrapper.m_RPGCharacter_Aim;
            public InputAction @WeaponDown => m_Wrapper.m_RPGCharacter_WeaponDown;
            public InputAction @WeaponLeft => m_Wrapper.m_RPGCharacter_WeaponLeft;
            public InputAction @WeaponRight => m_Wrapper.m_RPGCharacter_WeaponRight;
            public InputAction @WeaponUp => m_Wrapper.m_RPGCharacter_WeaponUp;
            public InputAction @Join => m_Wrapper.m_RPGCharacter_Join;
            public InputAction @Kick => m_Wrapper.m_RPGCharacter_Kick;
            public InputAction @Interact => m_Wrapper.m_RPGCharacter_Interact;
            public InputActionMap Get() { return m_Wrapper.m_RPGCharacter; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(RPGCharacterActions set) { return set.Get(); }
            public void SetCallbacks(IRPGCharacterActions instance)
            {
                if (m_Wrapper.m_RPGCharacterActionsCallbackInterface != null)
                {
                    @AttackL.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAttackL;
                    @AttackL.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAttackL;
                    @AttackL.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAttackL;
                    @AttackR.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAttackR;
                    @AttackR.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAttackR;
                    @AttackR.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAttackR;
                    @Block.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnBlock;
                    @Block.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnBlock;
                    @Block.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnBlock;
                    @CastL.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnCastL;
                    @CastL.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnCastL;
                    @CastL.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnCastL;
                    @CastR.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnCastR;
                    @CastR.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnCastR;
                    @CastR.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnCastR;
                    @Death.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnDeath;
                    @Death.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnDeath;
                    @Death.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnDeath;
                    @Face.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnFace;
                    @Face.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnFace;
                    @Face.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnFace;
                    @Facing.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnFacing;
                    @Facing.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnFacing;
                    @Facing.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnFacing;
                    @Jump.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnJump;
                    @LightHit.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnLightHit;
                    @LightHit.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnLightHit;
                    @LightHit.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnLightHit;
                    @Move.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnMove;
                    @Relax.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnRelax;
                    @Relax.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnRelax;
                    @Relax.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnRelax;
                    @Roll.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnRoll;
                    @Roll.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnRoll;
                    @Roll.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnRoll;
                    @Shield.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnShield;
                    @Shield.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnShield;
                    @Shield.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnShield;
                    @Aim.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAim;
                    @Aim.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAim;
                    @Aim.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnAim;
                    @WeaponDown.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponDown;
                    @WeaponDown.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponDown;
                    @WeaponDown.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponDown;
                    @WeaponLeft.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponLeft;
                    @WeaponLeft.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponLeft;
                    @WeaponLeft.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponLeft;
                    @WeaponRight.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponRight;
                    @WeaponRight.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponRight;
                    @WeaponRight.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponRight;
                    @WeaponUp.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponUp;
                    @WeaponUp.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponUp;
                    @WeaponUp.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnWeaponUp;
                    @Join.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnJoin;
                    @Join.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnJoin;
                    @Join.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnJoin;
                    @Kick.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnKick;
                    @Kick.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnKick;
                    @Kick.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnKick;
                    @Interact.started -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_RPGCharacterActionsCallbackInterface.OnInteract;
                }
                m_Wrapper.m_RPGCharacterActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @AttackL.started += instance.OnAttackL;
                    @AttackL.performed += instance.OnAttackL;
                    @AttackL.canceled += instance.OnAttackL;
                    @AttackR.started += instance.OnAttackR;
                    @AttackR.performed += instance.OnAttackR;
                    @AttackR.canceled += instance.OnAttackR;
                    @Block.started += instance.OnBlock;
                    @Block.performed += instance.OnBlock;
                    @Block.canceled += instance.OnBlock;
                    @CastL.started += instance.OnCastL;
                    @CastL.performed += instance.OnCastL;
                    @CastL.canceled += instance.OnCastL;
                    @CastR.started += instance.OnCastR;
                    @CastR.performed += instance.OnCastR;
                    @CastR.canceled += instance.OnCastR;
                    @Death.started += instance.OnDeath;
                    @Death.performed += instance.OnDeath;
                    @Death.canceled += instance.OnDeath;
                    @Face.started += instance.OnFace;
                    @Face.performed += instance.OnFace;
                    @Face.canceled += instance.OnFace;
                    @Facing.started += instance.OnFacing;
                    @Facing.performed += instance.OnFacing;
                    @Facing.canceled += instance.OnFacing;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @LightHit.started += instance.OnLightHit;
                    @LightHit.performed += instance.OnLightHit;
                    @LightHit.canceled += instance.OnLightHit;
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Relax.started += instance.OnRelax;
                    @Relax.performed += instance.OnRelax;
                    @Relax.canceled += instance.OnRelax;
                    @Roll.started += instance.OnRoll;
                    @Roll.performed += instance.OnRoll;
                    @Roll.canceled += instance.OnRoll;
                    @Shield.started += instance.OnShield;
                    @Shield.performed += instance.OnShield;
                    @Shield.canceled += instance.OnShield;
                    @Aim.started += instance.OnAim;
                    @Aim.performed += instance.OnAim;
                    @Aim.canceled += instance.OnAim;
                    @WeaponDown.started += instance.OnWeaponDown;
                    @WeaponDown.performed += instance.OnWeaponDown;
                    @WeaponDown.canceled += instance.OnWeaponDown;
                    @WeaponLeft.started += instance.OnWeaponLeft;
                    @WeaponLeft.performed += instance.OnWeaponLeft;
                    @WeaponLeft.canceled += instance.OnWeaponLeft;
                    @WeaponRight.started += instance.OnWeaponRight;
                    @WeaponRight.performed += instance.OnWeaponRight;
                    @WeaponRight.canceled += instance.OnWeaponRight;
                    @WeaponUp.started += instance.OnWeaponUp;
                    @WeaponUp.performed += instance.OnWeaponUp;
                    @WeaponUp.canceled += instance.OnWeaponUp;
                    @Join.started += instance.OnJoin;
                    @Join.performed += instance.OnJoin;
                    @Join.canceled += instance.OnJoin;
                    @Kick.started += instance.OnKick;
                    @Kick.performed += instance.OnKick;
                    @Kick.canceled += instance.OnKick;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                }
            }
        }
        public RPGCharacterActions @RPGCharacter => new RPGCharacterActions(this);
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_MouseandKeyboardSchemeIndex = -1;
        public InputControlScheme MouseandKeyboardScheme
        {
            get
            {
                if (m_MouseandKeyboardSchemeIndex == -1) m_MouseandKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse and Keyboard");
                return asset.controlSchemes[m_MouseandKeyboardSchemeIndex];
            }
        }
        public interface IRPGCharacterActions
        {
            void OnAttackL(InputAction.CallbackContext context);
            void OnAttackR(InputAction.CallbackContext context);
            void OnBlock(InputAction.CallbackContext context);
            void OnCastL(InputAction.CallbackContext context);
            void OnCastR(InputAction.CallbackContext context);
            void OnDeath(InputAction.CallbackContext context);
            void OnFace(InputAction.CallbackContext context);
            void OnFacing(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnLightHit(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnRelax(InputAction.CallbackContext context);
            void OnRoll(InputAction.CallbackContext context);
            void OnShield(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnWeaponDown(InputAction.CallbackContext context);
            void OnWeaponLeft(InputAction.CallbackContext context);
            void OnWeaponRight(InputAction.CallbackContext context);
            void OnWeaponUp(InputAction.CallbackContext context);
            void OnJoin(InputAction.CallbackContext context);
            void OnKick(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
        }
    }
}
